# Wie dieser Kurs funktoniert {.unnumbered}

An sich sollten die mehr oder weniger selbsterklärend sein: Im ersten Skript steht da zunächst, was in der Einheit dran kommt und warum. Dann folgen die einzelnen Videos (diese anschauen, Notizen machen) mit kurzen schriftlichen Zusammenfassungen und/oder zusätzlichen Erläuterungen. Nach dem Schauen eines Videos wechselt man zum zweiten Skript, und beantwortet die dazu gehörigen Fragen. Das dient der Selbstüberprüfung, ob man alles verstanden hat – daher gibt es dazu auch Lösungen im Skript. Diese Fragen stellen gleichzeitig den Inhalt dar, den man aus diesem Kapitel mitnehmen, d.h. (für die Prüfung sowie das spätere Leben) wissen sollte (soviel ist man den Steuerzahler*innen dann doch schuldig). Dann geht es weiter zum nächsten Kapitel, bis man alle Kapitel der Einheit durch hat.
In der Präsenzphase nächste Woche sprechen wir die Instant Reviews/Quiz nicht durch – allerdings können und werden wir natürlich Fragen oder Unklarheiten besprechen. Ansonsten werde ich Übungen mitbringen, welche die gesamte Einheit noch mal in einen Sinnzusammenhang stellt (so der Plan). Mit fortschreitendem Kurs wird der Sinnzusammenhang der Aufgaben dann immer weiter über mehrere/alle Einheiten erweitert, sodass nicht für sich stehende Wissenbrocken gelernt werden, sondern was diese im Zusammenhang bedeuten, bzw. wie wir mit diesen die Erde verstehen, bzw. sich darüber die Geochemie konstituiert. Das ist die Idee der ›Flipped Classroom‹ Methode.
