---
title: Literatur
--- 

# Kommentiertes Literaturverzeichnis {.unnumbered}

**Llovet+ 2020. Electron probe microanalysis: a review of recent developments and applications in materials science and engineering.**  
Prog Mater Sci 116 p, 100673 [doi](https://doi.org/10.1016/j.pmatsci.2020.100673)  
Ein sehr übersichtlicher Review-Artikel, der alle wichtigen Aspekte zur Mikrosonde auf ca. 90 Seiten zusammen fasst.

**Hawkes+Spence (Eds.) 2019. Handbook of Microscopy.**  
1543 p, Springer, Springer Nature Switzerland. [doi](https://doi.org/10.1007/978-3-030-00069-1)  
Ein gewaltiges Kompendium, das auf 1500 Seiten in vielen Einzelartikeln umfassend alle Aspekte der Elektronen-Mikroskopie abarbeitet. Die Mikrosonde fehlt, da sie offensichtlich mehr in die chemische Analytik und nicht die Mikroskopie fällt.

**Goldstein+ 2018. Scanning Electron Microscopy and X-Ray Microanalysis.**  
Second Edition, Plenum Press, New York [doi](https://link.springer.com/book/10.1007/978-1-4939-6676-9)  
Das Standardwerk beschreibt alles wichtige zur Mikrosonde in Einzelartikeln auf gut 500 Seiten.

**Rinaldi+Llovet 2015. Electron Probe Microanalysis: A Review of the Past, Present, and Future.**  
Microsc Microanal 21, 1053–1069 [doi](https://doi.org/10.1017/S1431927615000409)  
Ein interessanter Review-Artikel, der auch auf geschichtliche Aspekte der Mikrosonde eingeht.

**Reed, S. J. B. 2005. Electron Microprobe Analysis and Scanning Electron Microscopy in Geology.**  
Cambridge University Press. [doi](https://www.cambridge.org/core/books/electron-microprobe-analysis-and-scanning-electron-microscopy-in-geology/A7BD5CF9A6E6D9E2360E4F378C81D002)  
Das kompakte Buch fasst alles Wichtige zur Mikrosonde und dem REM auf gut 180 Seiten zusammen.